version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - nestjs_postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-nw

volumes:
  nestjs_postgres_data:
    driver: local

networks:
  nestjs-nw:
    driver: bridge
